### ISSUE TITLE
Adding github actions to automate deploy on shared hosting

### ISSUE THREAD

**Issue by RemcoHalman** [EddieJaoudeCommunity/support#163]
**Portfolio Website**

I would like to auto deploy my portfolio website through Github actions, now is my question where to start, i'm using shard hosting with SSH acces. If i manually pull down my newer version from Github it works.

But i want to (hope to) update my portfolio items frequently. So it will be a little tedious to do a upload(Github) and pull down on my hosting.

any tips i'm all ears

**Comment by eddiejaoude** [comment]
If you have `ssh` access to your shared hosting, you can `scp` the files to the shared hosting with a GitHub Action.

1. GitHub Action that triggers on a branch or release
2. GitHub Secret for the `ssh` key
3. GitHub Action checks out the code and `scp` the files to your shared hosting over `ssh`
4. Website deploy 🎉 

There are GitHub Actions that do this already, so you need to just pass the config variables for it https://github.com/marketplace/actions/ssh-deploy

```yaml
  - name: Deploy to Staging server
    uses: easingthemes/ssh-deploy@v2.0.7
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      ARGS: "-rltgoDzvO"
      SOURCE: "dist/"
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      TARGET: ${{ secrets.REMOTE_TARGET }}
```
