### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by mariuscernescu** [EddieJaoudeCommunity/support#491]
Please invite me to the GitHub Community Organisation. 

Name: Marius Cernescu

Discord Username(if exists): 
mariuscernescu#8328

Additional Context: 
I watched his video on the Traversy Media youtube channel and inspired me to come and join the community.
I was already looking for a way to join and this came at the right time.

 
I would like to contribute to open-source software and be part of the process of advancing technology.
:nerd_face:

**Comment by dumbcoder7** [comment]
Hey Marius, you'll probably be soon accepted into the community.
Just a request, try to avoid assigning the maintainers these issues. They are sure to get back to it in a day or two. 
Also, hop into the Discord server!

**Comment by mariuscernescu** [comment]
Hey dumbcoder7,
I am not sure that I understand what  ` avoid assigning the maintainers these issues.` means. If it means that I have to wait that is not a problem.
I'll see you on discord!

**Comment by eddiejaoude** [comment]
@dumbcoder7 thank you for supporting our community. Some issues have auto assign from the Issue templates. This one has auto assign, but the label did not get added for some reason, we might have a bug in the template.

Here is the template config

```yaml
---
name: Invitation to the GitHub Community Organization
about: I would like to be part of the awesome community
title: 'Please invite me to the GitHub Community Organization'
labels: 'invite me to the organization'
assignees: eddiejaoude, mikeysan
---
```

Full template link https://github.com/EddieJaoudeCommunity/support/blob/main/.github/ISSUE_TEMPLATE/invitation.md

I hope that helps. Any questions let me know 🤓
